name: youapp_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
  dropdown_button2: ^2.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_bloc: ^8.1.3
  flutter_input_chips: ^1.0.3
  flutter_svg: ^2.0.6
  get: ^4.6.5
  get_it: ^7.6.0
  google_fonts: 3.0.1
  http: 0.13.4
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  logger: ^1.3.0
  material_dialogs: ^1.1.4
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  simple_gradient_text: ^1.2.4

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  mocktail: ^0.3.0
  test_cov_console: ^0.2.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
